# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0.0
  codecov: codecov/codecov@3.2.2

jobs:
  test:
    parameters:
      node-version:
        default: "lts"
        description: The target version of Node.js to run tests against.
        type: string
      slonik-version:
        description: The target version of Slonik to run tests against.
        type: string
      mocha-slonik-version:
        description: The target version of Mocha Slonik to run tests against.
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
      - image: cimg/postgres:13.8
        environment:
          POSTGRES_PASSWORD: circleci_test
    working_directory: ~/express-slonik
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install Slonik v<< parameters.slonik-version >> & mocha-slonik v<< parameters.mocha-slonik-version >>
          command: npm install slonik@<< parameters.slonik-version >> mocha-slonik@<< parameters.mocha-slonik-version >>
      - run:
          name: Run tests
          command: PROPERTIES="BRANCH:${CIRCLE_BRANCH},BUILD_NUM:${CIRCLE_BUILD_NUM},COMMIT:${CIRCLE_SHA1}" npm run test:ci
          environment:
            NODE_ENV: test
            MOCHA_FILE: ./tests/results/mocha/results.xml
            DATABASE_URL: postgres://postgres:circleci_test@localhost:5432/circle_test
      - codecov/upload
      - store_test_results:
          path: tests/results
  build:
    docker:
      - image: cimg/node:lts
    working_directory: ~/express-slonik
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build package
          command: |
            mkdir package
            npm pack --pack-destination package
      - persist_to_workspace:
          root: .
          paths:
            - "*"
      - store_artifacts:
          path: package
          destination: .
  publish:
    docker:
      - image: cimg/node:lts
    working_directory: ~/express-slonik
    steps:
      - attach_workspace:
          at: ~/express-slonik
      - run:
          name: Set NPM token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run: npm publish
      - unless:
          condition: << pipeline.git.tag >>
          steps:
            - run: npm publish --dry-run
  release:
    docker:
      - image: cimg/node:lts
    working_directory: ~/express-slonik
    steps:
      - add_ssh_keys:
          fingerprints:
            - "79:df:47:6a:ab:d1:08:40:ae:41:a1:76:c5:77:ac:56"
      - checkout
      - run:
          name: Import GPG key
          command: echo -e "${GPG_KEY}" | base64 -d | gunzip | gpg --batch --yes --import
      - run:
          name: Set up GPG Script
          command: |
            echo '/usr/bin/gpg --batch --no-tty --passphrase ${GPG_PASSPHRASE} --pinentry-mode loopback "$@"' > /tmp/gpg-with-passphrase
            chmod +x /tmp/gpg-with-passphrase
      - run:
          name: Configure Git client
          command: |
            git config gpg.program "/tmp/gpg-with-passphrase"
            git config commit.gpgsign true
            git config --global user.signingkey ${GPG_KEY_ID}
            git config --global user.email bot@andrewjo.com
            git config --global user.name "Semantic Release Bot"
      - node/install-packages
      - run:
          name: Run semantic-release
          command: npm run semantic-release
workflows:
  build-and-release:
    jobs:
      - test:
          name: test-node-v<< matrix.node-version >>-slonik-v<< matrix.slonik-version >>-mocha-slonik-v<< matrix.mocha-slonik-version >>
          context: test
          filters:
            tags:
              only: /v\d+(?:\.\d+){0,2}(?:-\w+(?:\.\w+)*){0,1}/
          matrix:
            parameters:
              node-version: ["16.19", "18.18"]
              slonik-version: ["33.3.3", "34.3.0", "35.2.1", "36.0.0", "37.0.1"]
              mocha-slonik-version: ["7.0.1", "8.0.0", "9.0.0"]
            exclude:
              - node-version: "16.19"
                slonik-version: "33.3.3"
                mocha-slonik-version: "9.0.0"
              - node-version: "18.18"
                slonik-version: "33.3.3"
                mocha-slonik-version: "9.0.0"
              - node-version: "16.19"
                slonik-version: "34.3.0"
                mocha-slonik-version: "9.0.0"
              - node-version: "18.18"
                slonik-version: "34.3.0"
                mocha-slonik-version: "9.0.0"
              - node-version: "16.19"
                slonik-version: "33.3.3"
                mocha-slonik-version: "8.0.0"
              - node-version: "18.18"
                slonik-version: "33.3.3"
                mocha-slonik-version: "8.0.0"
              - node-version: "16.19"
                slonik-version: "35.2.1"
                mocha-slonik-version: "8.0.0"
              - node-version: "18.18"
                slonik-version: "35.2.1"
                mocha-slonik-version: "8.0.0"
              - node-version: "16.19"
                slonik-version: "36.0.0"
                mocha-slonik-version: "8.0.0"
              - node-version: "18.18"
                slonik-version: "36.0.0"
                mocha-slonik-version: "8.0.0"
              - node-version: "16.19"
                slonik-version: "37.0.1"
                mocha-slonik-version: "8.0.0"
              - node-version: "18.18"
                slonik-version: "37.0.1"
                mocha-slonik-version: "8.0.0"
              - node-version: "16.19"
                slonik-version: "34.3.0"
                mocha-slonik-version: "7.0.1"
              - node-version: "18.18"
                slonik-version: "34.3.0"
                mocha-slonik-version: "7.0.1"
              - node-version: "16.19"
                slonik-version: "35.2.1"
                mocha-slonik-version: "7.0.1"
              - node-version: "18.18"
                slonik-version: "35.2.1"
                mocha-slonik-version: "7.0.1"
              - node-version: "16.19"
                slonik-version: "36.0.0"
                mocha-slonik-version: "7.0.1"
              - node-version: "18.18"
                slonik-version: "36.0.0"
                mocha-slonik-version: "7.0.1"
              - node-version: "16.19"
                slonik-version: "37.0.1"
                mocha-slonik-version: "7.0.1"
              - node-version: "18.18"
                slonik-version: "37.0.1"
                mocha-slonik-version: "7.0.1"
      - release:
          context:
            - npm
            - semantic-release
          requires:
            - test
